steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v2.0.0:
        id: seek-oss/package-publishing

  - label: ":no_entry_sign: :npm: :package: :hammer:"
    plugins:
      docker-compose#v2.5.0:
        run: tests
